import React, { createContext, useContext, useState, useCallback, ReactNode } from 'react';

// Types
export type Resource = {
  id: string;
  title: string;
  description: string;
  link: string;
  icon: string; // Icon name from lucide-react
};

export type SidebarItem = {
  id: string;
  type: 'link' | 'category' | 'html' | 'doc' | 'autogenerated';
  label?: string;
  href?: string;
  items?: SidebarItem[];
  dirName?: string;
  value?: string;
  collapsible?: boolean;
  collapsed?: boolean;
  link?: {
    type: 'generated-index' | 'doc';
  };
};

export type ArticleContent = {
  docId: string;
  title: string;
  content: string; // HTML content from rich text editor
  frontmatter: Record<string, any>;
};

export type CMSConfig = {
  landingPage: {
    heroTitle: string;
    heroSubtitle: string;
    featuredHeading: string;
    featuredSubtitle: string;
    roleHeading: string;
    roleSubtitle: string;
    learnMoreHeading: string;
    learnMoreSubtitle: string;
    coreResources: Resource[];
    featuredResources: Resource[];
    roleResources: Resource[];
    learnMoreResources: Resource[];
  };
  sidebar: SidebarItem[];
  articles: Record<string, ArticleContent>;
};

interface CMSContextType {
  config: CMSConfig;
  isDirty: boolean;
  isEditMode: boolean;
  setEditMode: (enabled: boolean) => void;
  updateLandingPage: (section: keyof CMSConfig['landingPage'], resources: Resource[]) => void;
  updateHeroText: (title: string, subtitle: string) => void;
  updateSectionText: (section: 'featured' | 'role' | 'learnMore', heading: string, subtitle: string) => void;
  updateSidebar: (sidebar: SidebarItem[]) => void;
  updateArticle: (docId: string, content: ArticleContent) => void;
  addResource: (section: keyof CMSConfig['landingPage'], resource: Resource) => void;
  removeResource: (section: keyof CMSConfig['landingPage'], id: string) => void;
  addSidebarItem: (parentId: string | null, item: SidebarItem) => void;
  removeSidebarItem: (id: string) => void;
  renameSidebarItem: (id: string, newLabel: string) => void;
  moveSidebarItem: (itemId: string, newParentId: string | null) => void;
  exportConfig: () => string;
  loadConfig: (config: CMSConfig) => void;
  markDirty: () => void;
  markClean: () => void;
}

const CMSContext = createContext<CMSContextType | undefined>(undefined);

// Default config based on current structure
const defaultConfig: CMSConfig = {
  landingPage: {
    heroTitle: 'GCXONE Documentation',
    heroSubtitle: 'An extensive database of instructions for working in the GCXONE ecosystem.',
    featuredHeading: 'Featured Topics',
    featuredSubtitle: 'Explore key areas of the GCXONE platform.',
    roleHeading: 'Learn by role',
    roleSubtitle: 'View GCXONE documentation for your user role.',
    learnMoreHeading: 'Learn more',
    learnMoreSubtitle: 'Use our Help Center and browse our videos and articles.',
    coreResources: [
      {
        id: 'core-1',
        title: 'Get Started',
        description: 'A collection of tutorials to help you with your first steps in GCXONE.',
        link: '/docs/platform-fundamentals/what-is-gcxone-GCXONE',
        icon: 'Rocket',
      },
      {
        id: 'core-2',
        title: 'GCXONE Platform',
        description: 'The fully managed alarm management platform you can use to automate repetitive tasks.',
        link: '/docs/platform-fundamentals/what-is-gcxone-GCXONE',
        icon: 'LayoutDashboard',
      },
      {
        id: 'core-3',
        title: 'Devices',
        description: 'Reliable alarm transmission, remote access, and data interfaces to IoT devices.',
        link: '/docs/device-integration/standard-device-onboarding-process',
        icon: 'Server',
      },
      {
        id: 'core-4',
        title: 'API',
        description: 'Step-by-step guides to integrate with the GCXONE API.',
        link: '/docs/internal/technical-architecture/microservices-proxy-architecture',
        icon: 'Code2',
      },
    ],
    featuredResources: [
      {
        id: 'featured-1',
        title: 'Platform Overview',
        description: 'Learn about the core concepts and architecture of the GCXONE platform.',
        link: '/docs/platform-fundamentals/what-is-gcxone-GCXONE',
        icon: 'BookOpen',
      },
      {
        id: 'featured-2',
        title: 'Admin Guide',
        description: 'A comprehensive guide for administrators to manage and configure the platform.',
        link: '/docs/account-management/how-to-add-a-customer',
        icon: 'ShieldCheck',
      },
      {
        id: 'featured-3',
        title: 'Device Integration',
        description: 'Find guides for integrating a wide variety of third-party devices.',
        link: '/docs/device-integration/standard-device-onboarding-process',
        icon: 'Cpu',
      },
    ],
    roleResources: [
      {
        id: 'role-1',
        title: 'For Admin',
        description: 'Administrator configures GCXONE settings for all types of users and has full permissions.',
        link: '/docs/account-management/managing-users-and-roles',
        icon: 'Shield',
      },
      {
        id: 'role-2',
        title: 'For Operator',
        description: 'Operator processes alarms and has permissions to view most GCXONE objects.',
        link: '/docs/features-operations/dashboard-navigation-guide',
        icon: 'Activity',
      },
      {
        id: 'role-3',
        title: 'For Installer',
        description: 'Installer manages device provisioning, site setup, and diagnostics tools.',
        link: '/docs/device-integration/standard-device-onboarding-process',
        icon: 'Wrench',
      },
      {
        id: 'role-4',
        title: 'For Developer',
        description: 'Developer integrates third-party systems using the RESTful API.',
        link: '/docs/internal/technical-architecture/microservices-proxy-architecture',
        icon: 'Code2',
      },
    ],
    learnMoreResources: [
      {
        id: 'learn-1',
        title: 'Help Center',
        description: 'Submit tickets, and get answers to the most common questions.',
        link: '/docs/troubleshooting-support/how-to-submit-a-support-ticket',
        icon: 'HelpCircle',
      },
      {
        id: 'learn-2',
        title: 'Tutorials',
        description: 'How-to videos for all levels of users.',
        link: '/docs/platform-fundamentals/what-is-gcxone-GCXONE',
        icon: 'PlayCircle',
      },
      {
        id: 'learn-3',
        title: 'Release Notes',
        description: 'All things about alarm management updates and GCXONE releases.',
        link: '/docs/platform-fundamentals/what-is-gcxone-GCXONE',
        icon: 'FileText',
      },
    ],
  },
  sidebar: [
    {
      id: 'sidebar-home',
      type: 'link',
      label: 'Home',
      href: '/',
    },
    {
      id: 'sidebar-platform',
      type: 'category',
      label: 'Platform Fundamentals',
      link: { type: 'generated-index' },
      collapsible: true,
      collapsed: false,
      items: [
        {
          id: 'sidebar-platform-doc',
          type: 'autogenerated',
          dirName: '01-platform-fundamentals',
        },
      ],
    },
    {
      id: 'sidebar-account',
      type: 'category',
      label: 'Account Management',
      link: { type: 'generated-index' },
      collapsible: true,
      collapsed: true,
      items: [
        {
          id: 'sidebar-account-doc',
          type: 'autogenerated',
          dirName: '02-account-management',
        },
      ],
    },
  ],
  articles: {},
};

export function CMSProvider({ children }: { children: ReactNode }) {
  const [config, setConfig] = useState<CMSConfig>(() => {
    // Only try to load from localStorage on the client side
    if (typeof window === 'undefined') {
      return defaultConfig;
    }

    try {
      const saved = localStorage.getItem('cms_config');
      if (saved) {
        const parsed = JSON.parse(saved);
        // Merge with default to ensure all fields exist
        return {
          ...defaultConfig,
          ...parsed,
          landingPage: {
            ...defaultConfig.landingPage,
            ...parsed.landingPage,
          },
        };
      }
    } catch {
      return defaultConfig;
    }

    return defaultConfig;
  });
  const [isDirty, setIsDirty] = useState(false);
  const [isEditMode, setIsEditMode] = useState(false);

  const markDirty = useCallback(() => setIsDirty(true), []);
  const markClean = useCallback(() => setIsDirty(false), []);

  const updateLandingPage = useCallback(
    (section: keyof CMSConfig['landingPage'], resources: Resource[]) => {
      setConfig((prev) => ({
        ...prev,
        landingPage: {
          ...prev.landingPage,
          [section]: resources,
        },
      }));
      markDirty();
    },
    [markDirty]
  );

  const updateHeroText = useCallback(
    (title: string, subtitle: string) => {
      setConfig((prev) => ({
        ...prev,
        landingPage: {
          ...prev.landingPage,
          heroTitle: title,
          heroSubtitle: subtitle,
        },
      }));
      markDirty();
    },
    [markDirty]
  );

  const updateSectionText = useCallback(
    (section: 'featured' | 'role' | 'learnMore', heading: string, subtitle: string) => {
      setConfig((prev) => ({
        ...prev,
        landingPage: {
          ...prev.landingPage,
          [`${section}Heading`]: heading,
          [`${section}Subtitle`]: subtitle,
        },
      }));
      markDirty();
    },
    [markDirty]
  );

  const updateSidebar = useCallback(
    (sidebar: SidebarItem[]) => {
      setConfig((prev) => ({ ...prev, sidebar }));
      markDirty();
    },
    [markDirty]
  );

  const updateArticle = useCallback(
    (docId: string, content: ArticleContent) => {
      setConfig((prev) => ({
        ...prev,
        articles: {
          ...prev.articles,
          [docId]: content,
        },
      }));
      markDirty();
    },
    [markDirty]
  );

  const addResource = useCallback(
    (section: keyof CMSConfig['landingPage'], resource: Resource) => {
      setConfig((prev) => {
        const sectionData = prev.landingPage[section];
        if (Array.isArray(sectionData)) {
          return {
            ...prev,
            landingPage: {
              ...prev.landingPage,
              [section]: [...sectionData, resource],
            },
          };
        }
        return prev;
      });
      markDirty();
    },
    [markDirty]
  );

  const removeResource = useCallback(
    (section: keyof CMSConfig['landingPage'], id: string) => {
      setConfig((prev) => {
        const sectionData = prev.landingPage[section];
        if (Array.isArray(sectionData)) {
          return {
            ...prev,
            landingPage: {
              ...prev.landingPage,
              [section]: sectionData.filter((r) => r.id !== id),
            },
          };
        }
        return prev;
      });
      markDirty();
    },
    [markDirty]
  );

  const findSidebarItem = useCallback((items: SidebarItem[], id: string): SidebarItem | null => {
    for (const item of items) {
      if (item.id === id) return item;
      if (item.items) {
        const found = findSidebarItem(item.items, id);
        if (found) return found;
      }
    }
    return null;
  }, []);

  const removeSidebarItemRecursive = useCallback(
    (items: SidebarItem[], id: string): SidebarItem[] => {
      return items
        .filter((item) => item.id !== id)
        .map((item) => ({
          ...item,
          items: item.items ? removeSidebarItemRecursive(item.items, id) : undefined,
        }));
    },
    []
  );

  const removeSidebarItem = useCallback(
    (id: string) => {
      setConfig((prev) => ({
        ...prev,
        sidebar: removeSidebarItemRecursive(prev.sidebar, id),
      }));
      markDirty();
    },
    [markDirty, removeSidebarItemRecursive]
  );

  const renameSidebarItem = useCallback(
    (id: string, newLabel: string) => {
      const renameRecursive = (items: SidebarItem[]): SidebarItem[] => {
        return items.map((item) => ({
          ...item,
          label: item.id === id ? newLabel : item.label,
          items: item.items ? renameRecursive(item.items) : undefined,
        }));
      };

      setConfig((prev) => ({
        ...prev,
        sidebar: renameRecursive(prev.sidebar),
      }));
      markDirty();
    },
    [markDirty]
  );

  const addSidebarItem = useCallback(
    (parentId: string | null, item: SidebarItem) => {
      if (!parentId) {
        setConfig((prev) => ({
          ...prev,
          sidebar: [...prev.sidebar, item],
        }));
      } else {
        const addRecursive = (items: SidebarItem[]): SidebarItem[] => {
          return items.map((i) => {
            if (i.id === parentId) {
              return {
                ...i,
                items: [...(i.items || []), item],
              };
            }
            return {
              ...i,
              items: i.items ? addRecursive(i.items) : undefined,
            };
          });
        };

        setConfig((prev) => ({
          ...prev,
          sidebar: addRecursive(prev.sidebar),
        }));
      }
      markDirty();
    },
    [markDirty]
  );

  const moveSidebarItem = useCallback(
    (itemId: string, newParentId: string | null) => {
      let itemToMove: SidebarItem | null = null;
      
      const removeItem = (items: SidebarItem[]): SidebarItem[] => {
        return items.filter(item => {
          if (item.id === itemId) {
            itemToMove = item;
            return false;
          }
          return {
            ...item,
            items: item.items ? removeItem(item.items) : undefined,
          };
        }).map(item => ({
          ...item,
          items: item.items ? removeItem(item.items) : undefined,
        }));
      };

      const insertItem = (items: SidebarItem[]): SidebarItem[] => {
        if (newParentId === null) {
          return [...items, itemToMove!];
        }
        return items.map(item => {
          if (item.id === newParentId) {
            return {
              ...item,
              items: [...(item.items || []), itemToMove!],
            };
          }
          return {
            ...item,
            items: item.items ? insertItem(item.items) : undefined,
          };
        });
      };

      setConfig(prev => {
        const withoutItem = removeItem(prev.sidebar);
        return {
          ...prev,
          sidebar: itemToMove ? insertItem(withoutItem) : prev.sidebar,
        };
      });
      markDirty();
    },
    [markDirty]
  );

  const exportConfig = useCallback(() => {
    return JSON.stringify(config, null, 2);
  }, [config]);

  const loadConfig = useCallback((newConfig: CMSConfig) => {
    setConfig(newConfig);
    if (typeof window !== 'undefined') {
      localStorage.setItem('cms_config', JSON.stringify(newConfig));
    }
    markClean();
  }, [markClean]);

  // Auto-save to localStorage
  React.useEffect(() => {
    if (isDirty && typeof window !== 'undefined') {
      localStorage.setItem('cms_config', JSON.stringify(config));
    }
  }, [config, isDirty]);

  return (
    <CMSContext.Provider
      value={{
        config,
        isDirty,
        isEditMode,
        setEditMode: setIsEditMode,
        updateLandingPage,
        updateHeroText,
        updateSectionText,
        updateSidebar,
        updateArticle,
        addResource,
        removeResource,
        addSidebarItem,
        removeSidebarItem,
        renameSidebarItem,
        moveSidebarItem,
        exportConfig,
        loadConfig,
        markDirty,
        markClean,
      }}
    >
      {children}
    </CMSContext.Provider>
  );
}

export function useCMS() {
  const context = useContext(CMSContext);
  if (!context) {
    throw new Error('useCMS must be used within CMSProvider');
  }
  return context;
}

