/**
 * Auto-generated sidebar from Confluence Surge space.
 * Generated by gcsurge/scripts/fetch-confluence-gcsurge.js
 * DO NOT EDIT MANUALLY.
 */
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  sanityDocsSidebar: [
      { type: 'doc', id: 'gc-surge-device-integration-with-nxgen-platform-api-email-and-ftp-methods', label: 'GC Surge Device Integration with NxGen Platform: API, Email, and FTP Methods' },
      { type: 'doc', id: 'gc-surge-api-integration-guide-for-sending-events-to-nxgen-platform', label: 'GC Surge API Integration Guide for Sending Events to NxGen Platform' },
      { type: 'doc', id: 'gc-surge-pricing-model', label: 'GC Surge Pricing Model' },
    {
      type: 'category',
      label: 'Device Integrations',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Email (SMTP)',
          collapsible: true,
          collapsed: true,
          items: [
      { type: 'doc', id: 'hikproconnect-smtp', label: 'HikProConnect SMTP' },
      { type: 'doc', id: 'adpro-smtp', label: 'ADPRO SMTP' },
      { type: 'doc', id: 'vivotek-smtp', label: 'Vivotek SMTP' },
      { type: 'doc', id: 'nxwittness-hanhwa-smpt', label: 'NXWiTTNeSS/Hanhwa SMPT' },
      { type: 'doc', id: 'dahua-smtp', label: 'Dahua SMTP' },
      { type: 'doc', id: 'hikvision-smtp', label: 'Hikvision SMTP' },
      { type: 'doc', id: 'axis-smtp', label: 'Axis SMTP' },
      { type: 'doc', id: 'axis-camera-station-pro-smtp', label: 'Axis Camera Station Pro SMTP' },
          ],
        },
        {
          type: 'category',
          label: 'FTP',
          collapsible: true,
          collapsed: true,
          items: [
      { type: 'doc', id: 'hikvision-ftp', label: 'HikVision FTP' },
      { type: 'doc', id: 'axis-ftp', label: 'Axis FTP' },
      { type: 'doc', id: 'vivotek-ip-camera-ftp', label: 'Vivotek IP Camera FTP' },
      { type: 'doc', id: 'ganz-ftp', label: 'Ganz FTP' },
      { type: 'doc', id: 'dahua-ftp', label: 'Dahua FTP' },
          ],
        },
      ],
    },
  ],
};

export default sidebars;
