//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  devices: Devices;
  devicesConnection: DevicesConnection;
  features: Features;
  featuresConnection: FeaturesConnection;
  platform: Platform;
  platformConnection: PlatformConnection;
  internal: Internal;
  internalConnection: InternalConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDevicesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDevicesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DevicesFilter>;
};


export type QueryFeaturesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryFeaturesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FeaturesFilter>;
};


export type QueryPlatformArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPlatformConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PlatformFilter>;
};


export type QueryInternalArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryInternalConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<InternalFilter>;
};

export type DocumentFilter = {
  devices?: InputMaybe<DevicesFilter>;
  features?: InputMaybe<FeaturesFilter>;
  platform?: InputMaybe<PlatformFilter>;
  internal?: InputMaybe<InternalFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Devices | Features | Platform | Internal | Folder;

export type Devices = Node & Document & {
  __typename?: 'Devices';
  title: Scalars['String']['output'];
  sidebar_label?: Maybe<Scalars['String']['output']>;
  sidebar_position?: Maybe<Scalars['Float']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type DevicesBodyInfoBoxFilter = {
  type?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type DevicesBodyCodeBlockFilter = {
  language?: InputMaybe<StringFilter>;
  code?: InputMaybe<StringFilter>;
};

export type DevicesBodyYouTubeFilter = {
  videoId?: InputMaybe<StringFilter>;
};

export type DevicesBodyFilter = {
  InfoBox?: InputMaybe<DevicesBodyInfoBoxFilter>;
  CodeBlock?: InputMaybe<DevicesBodyCodeBlockFilter>;
  YouTube?: InputMaybe<DevicesBodyYouTubeFilter>;
};

export type DevicesFilter = {
  title?: InputMaybe<StringFilter>;
  sidebar_label?: InputMaybe<StringFilter>;
  sidebar_position?: InputMaybe<NumberFilter>;
  description?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  body?: InputMaybe<DevicesBodyFilter>;
};

export type DevicesConnectionEdges = {
  __typename?: 'DevicesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Devices>;
};

export type DevicesConnection = Connection & {
  __typename?: 'DevicesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DevicesConnectionEdges>>>;
};

export type Features = Node & Document & {
  __typename?: 'Features';
  title: Scalars['String']['output'];
  sidebar_label?: Maybe<Scalars['String']['output']>;
  sidebar_position?: Maybe<Scalars['Float']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type FeaturesFilter = {
  title?: InputMaybe<StringFilter>;
  sidebar_label?: InputMaybe<StringFilter>;
  sidebar_position?: InputMaybe<NumberFilter>;
  description?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type FeaturesConnectionEdges = {
  __typename?: 'FeaturesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Features>;
};

export type FeaturesConnection = Connection & {
  __typename?: 'FeaturesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<FeaturesConnectionEdges>>>;
};

export type Platform = Node & Document & {
  __typename?: 'Platform';
  title: Scalars['String']['output'];
  sidebar_label?: Maybe<Scalars['String']['output']>;
  sidebar_position?: Maybe<Scalars['Float']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PlatformFilter = {
  title?: InputMaybe<StringFilter>;
  sidebar_label?: InputMaybe<StringFilter>;
  sidebar_position?: InputMaybe<NumberFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type PlatformConnectionEdges = {
  __typename?: 'PlatformConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Platform>;
};

export type PlatformConnection = Connection & {
  __typename?: 'PlatformConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PlatformConnectionEdges>>>;
};

export type Internal = Node & Document & {
  __typename?: 'Internal';
  title: Scalars['String']['output'];
  sidebar_label?: Maybe<Scalars['String']['output']>;
  sidebar_position?: Maybe<Scalars['Float']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type InternalFilter = {
  title?: InputMaybe<StringFilter>;
  sidebar_label?: InputMaybe<StringFilter>;
  sidebar_position?: InputMaybe<NumberFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type InternalConnectionEdges = {
  __typename?: 'InternalConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Internal>;
};

export type InternalConnection = Connection & {
  __typename?: 'InternalConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<InternalConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateDevices: Devices;
  createDevices: Devices;
  updateFeatures: Features;
  createFeatures: Features;
  updatePlatform: Platform;
  createPlatform: Platform;
  updateInternal: Internal;
  createInternal: Internal;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateDevicesArgs = {
  relativePath: Scalars['String']['input'];
  params: DevicesMutation;
};


export type MutationCreateDevicesArgs = {
  relativePath: Scalars['String']['input'];
  params: DevicesMutation;
};


export type MutationUpdateFeaturesArgs = {
  relativePath: Scalars['String']['input'];
  params: FeaturesMutation;
};


export type MutationCreateFeaturesArgs = {
  relativePath: Scalars['String']['input'];
  params: FeaturesMutation;
};


export type MutationUpdatePlatformArgs = {
  relativePath: Scalars['String']['input'];
  params: PlatformMutation;
};


export type MutationCreatePlatformArgs = {
  relativePath: Scalars['String']['input'];
  params: PlatformMutation;
};


export type MutationUpdateInternalArgs = {
  relativePath: Scalars['String']['input'];
  params: InternalMutation;
};


export type MutationCreateInternalArgs = {
  relativePath: Scalars['String']['input'];
  params: InternalMutation;
};

export type DocumentUpdateMutation = {
  devices?: InputMaybe<DevicesMutation>;
  features?: InputMaybe<FeaturesMutation>;
  platform?: InputMaybe<PlatformMutation>;
  internal?: InputMaybe<InternalMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  devices?: InputMaybe<DevicesMutation>;
  features?: InputMaybe<FeaturesMutation>;
  platform?: InputMaybe<PlatformMutation>;
  internal?: InputMaybe<InternalMutation>;
};

export type DevicesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  sidebar_label?: InputMaybe<Scalars['String']['input']>;
  sidebar_position?: InputMaybe<Scalars['Float']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type FeaturesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  sidebar_label?: InputMaybe<Scalars['String']['input']>;
  sidebar_position?: InputMaybe<Scalars['Float']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type PlatformMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  sidebar_label?: InputMaybe<Scalars['String']['input']>;
  sidebar_position?: InputMaybe<Scalars['Float']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type InternalMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  sidebar_label?: InputMaybe<Scalars['String']['input']>;
  sidebar_position?: InputMaybe<Scalars['Float']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type DevicesPartsFragment = { __typename: 'Devices', title: string, sidebar_label?: string | null, sidebar_position?: number | null, description?: string | null, tags?: Array<string | null> | null, body?: any | null };

export type FeaturesPartsFragment = { __typename: 'Features', title: string, sidebar_label?: string | null, sidebar_position?: number | null, description?: string | null, tags?: Array<string | null> | null, body?: any | null };

export type PlatformPartsFragment = { __typename: 'Platform', title: string, sidebar_label?: string | null, sidebar_position?: number | null, body?: any | null };

export type InternalPartsFragment = { __typename: 'Internal', title: string, sidebar_label?: string | null, sidebar_position?: number | null, body?: any | null };

export type DevicesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type DevicesQuery = { __typename?: 'Query', devices: { __typename: 'Devices', id: string, title: string, sidebar_label?: string | null, sidebar_position?: number | null, description?: string | null, tags?: Array<string | null> | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type DevicesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DevicesFilter>;
}>;


export type DevicesConnectionQuery = { __typename?: 'Query', devicesConnection: { __typename?: 'DevicesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'DevicesConnectionEdges', cursor: string, node?: { __typename: 'Devices', id: string, title: string, sidebar_label?: string | null, sidebar_position?: number | null, description?: string | null, tags?: Array<string | null> | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type FeaturesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type FeaturesQuery = { __typename?: 'Query', features: { __typename: 'Features', id: string, title: string, sidebar_label?: string | null, sidebar_position?: number | null, description?: string | null, tags?: Array<string | null> | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type FeaturesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FeaturesFilter>;
}>;


export type FeaturesConnectionQuery = { __typename?: 'Query', featuresConnection: { __typename?: 'FeaturesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'FeaturesConnectionEdges', cursor: string, node?: { __typename: 'Features', id: string, title: string, sidebar_label?: string | null, sidebar_position?: number | null, description?: string | null, tags?: Array<string | null> | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type PlatformQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PlatformQuery = { __typename?: 'Query', platform: { __typename: 'Platform', id: string, title: string, sidebar_label?: string | null, sidebar_position?: number | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PlatformConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PlatformFilter>;
}>;


export type PlatformConnectionQuery = { __typename?: 'Query', platformConnection: { __typename?: 'PlatformConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PlatformConnectionEdges', cursor: string, node?: { __typename: 'Platform', id: string, title: string, sidebar_label?: string | null, sidebar_position?: number | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type InternalQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type InternalQuery = { __typename?: 'Query', internal: { __typename: 'Internal', id: string, title: string, sidebar_label?: string | null, sidebar_position?: number | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type InternalConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<InternalFilter>;
}>;


export type InternalConnectionQuery = { __typename?: 'Query', internalConnection: { __typename?: 'InternalConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'InternalConnectionEdges', cursor: string, node?: { __typename: 'Internal', id: string, title: string, sidebar_label?: string | null, sidebar_position?: number | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const DevicesPartsFragmentDoc = gql`
    fragment DevicesParts on Devices {
  __typename
  title
  sidebar_label
  sidebar_position
  description
  tags
  body
}
    `;
export const FeaturesPartsFragmentDoc = gql`
    fragment FeaturesParts on Features {
  __typename
  title
  sidebar_label
  sidebar_position
  description
  tags
  body
}
    `;
export const PlatformPartsFragmentDoc = gql`
    fragment PlatformParts on Platform {
  __typename
  title
  sidebar_label
  sidebar_position
  body
}
    `;
export const InternalPartsFragmentDoc = gql`
    fragment InternalParts on Internal {
  __typename
  title
  sidebar_label
  sidebar_position
  body
}
    `;
export const DevicesDocument = gql`
    query devices($relativePath: String!) {
  devices(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...DevicesParts
  }
}
    ${DevicesPartsFragmentDoc}`;
export const DevicesConnectionDocument = gql`
    query devicesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: DevicesFilter) {
  devicesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...DevicesParts
      }
    }
  }
}
    ${DevicesPartsFragmentDoc}`;
export const FeaturesDocument = gql`
    query features($relativePath: String!) {
  features(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...FeaturesParts
  }
}
    ${FeaturesPartsFragmentDoc}`;
export const FeaturesConnectionDocument = gql`
    query featuresConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: FeaturesFilter) {
  featuresConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...FeaturesParts
      }
    }
  }
}
    ${FeaturesPartsFragmentDoc}`;
export const PlatformDocument = gql`
    query platform($relativePath: String!) {
  platform(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PlatformParts
  }
}
    ${PlatformPartsFragmentDoc}`;
export const PlatformConnectionDocument = gql`
    query platformConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PlatformFilter) {
  platformConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PlatformParts
      }
    }
  }
}
    ${PlatformPartsFragmentDoc}`;
export const InternalDocument = gql`
    query internal($relativePath: String!) {
  internal(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...InternalParts
  }
}
    ${InternalPartsFragmentDoc}`;
export const InternalConnectionDocument = gql`
    query internalConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: InternalFilter) {
  internalConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...InternalParts
      }
    }
  }
}
    ${InternalPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      devices(variables: DevicesQueryVariables, options?: C): Promise<{data: DevicesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DevicesQueryVariables, query: string}> {
        return requester<{data: DevicesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DevicesQueryVariables, query: string}, DevicesQueryVariables>(DevicesDocument, variables, options);
      },
    devicesConnection(variables?: DevicesConnectionQueryVariables, options?: C): Promise<{data: DevicesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DevicesConnectionQueryVariables, query: string}> {
        return requester<{data: DevicesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DevicesConnectionQueryVariables, query: string}, DevicesConnectionQueryVariables>(DevicesConnectionDocument, variables, options);
      },
    features(variables: FeaturesQueryVariables, options?: C): Promise<{data: FeaturesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FeaturesQueryVariables, query: string}> {
        return requester<{data: FeaturesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FeaturesQueryVariables, query: string}, FeaturesQueryVariables>(FeaturesDocument, variables, options);
      },
    featuresConnection(variables?: FeaturesConnectionQueryVariables, options?: C): Promise<{data: FeaturesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FeaturesConnectionQueryVariables, query: string}> {
        return requester<{data: FeaturesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FeaturesConnectionQueryVariables, query: string}, FeaturesConnectionQueryVariables>(FeaturesConnectionDocument, variables, options);
      },
    platform(variables: PlatformQueryVariables, options?: C): Promise<{data: PlatformQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PlatformQueryVariables, query: string}> {
        return requester<{data: PlatformQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PlatformQueryVariables, query: string}, PlatformQueryVariables>(PlatformDocument, variables, options);
      },
    platformConnection(variables?: PlatformConnectionQueryVariables, options?: C): Promise<{data: PlatformConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PlatformConnectionQueryVariables, query: string}> {
        return requester<{data: PlatformConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PlatformConnectionQueryVariables, query: string}, PlatformConnectionQueryVariables>(PlatformConnectionDocument, variables, options);
      },
    internal(variables: InternalQueryVariables, options?: C): Promise<{data: InternalQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: InternalQueryVariables, query: string}> {
        return requester<{data: InternalQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: InternalQueryVariables, query: string}, InternalQueryVariables>(InternalDocument, variables, options);
      },
    internalConnection(variables?: InternalConnectionQueryVariables, options?: C): Promise<{data: InternalConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: InternalConnectionQueryVariables, query: string}> {
        return requester<{data: InternalConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: InternalConnectionQueryVariables, query: string}, InternalConnectionQueryVariables>(InternalConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  