/**
 * Auto-generated sidebar configuration from Sanity.
 * This file is generated by scripts/generate-sidebars-from-sanity.js
 * DO NOT EDIT MANUALLY - changes will be overwritten.
 */
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  adminSidebar: [
    {
      type: "doc",
      id: "index",
      label: "Home"
    },
    {
      type: "category",
      label: "🗂️ Uncategorized",
      collapsible: true,
      collapsed: false,
      link: {
        type: "generated-index",
        description: "Docs automatically included in production sidebar without explicit sidebarCategory references.",
        slug: "/uncategorized"
      },
      items: [
        {
          type: "doc",
          id: "index",
          label: "Documentation Home"
        }
      ]
    }
  ],
};

export default sidebars;
