import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Fresh skeleton sidebar for internal docs - ready for new content
// All previous content has been moved to _migrated_content/docs-internal/
const sidebars: SidebarsConfig = {
  internalSidebar: [
    {
      type: 'html',
      value: '<a href="/" class="sidebar-logo-container"><img src="/img/Xo.png" alt="GCXONE Logo" /></a>',
      defaultStyle: true,
    },
    {
      type: 'category',
      label: 'Internal Documentation',
      collapsible: false,
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: '.' }
      ]
    },
  ],
};

export default sidebars;
