import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: ['getting-started/index', 'getting-started/account-setup'],
    },
    {
      type: 'category',
      label: 'Roles',
      items: ['roles/admin', 'roles/operator', 'roles/installer'],
    },
    {
      type: 'category',
      label: 'Features',
      items: [
        'features/index',
        'features/BulkImport/content',
        'features/CustomView/content',
        'features/Genie/content',
        'features/HealthCheck/content',
        'features/MarketPlace/content',
        'features/NOVA99x/content',
        'features/PulseView/content',
        'features/TimeSync/content',
        'features/TowerGuard/content',
        'features/ZenMode/content',
      ],
    },
    {
      type: 'category',
      label: 'Devices',
      items: [{ type: 'autogenerated', dirName: 'devices' }],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: ['api/index'],
    },
    {
      type: 'category',
      label: 'Release Notes',
      items: [{ type: 'autogenerated', dirName: 'release-notes' }],
    },
  ],
};

export default sidebars;
