/**
 * Auto-generated sidebar configuration from Sanity.
 * This file is generated by scripts/generate-sidebars-from-sanity.js
 * DO NOT EDIT MANUALLY - changes will be overwritten.
 */
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  sanityDocsSidebar: [
    {
      type: "doc",
      id: "index",
      label: "Documentation Home"
    },
    {
      type: "category",
      label: "🚀 Getting Started",
      collapsible: true,
      collapsed: false,
      link: {
        type: "generated-index",
        description: "Start here to learn the basics of NXGEN GCXONE platform",
        slug: "/getting-started"
      },
      items: [
        {
          type: "doc",
          id: "getting-started/what-is-gcxone",
          label: "What is GCXOne"
        },
        {
          type: "doc",
          id: "getting-started/pre-deployment-requirements",
          label: "Pre-Deployment Requirements"
        },
        {
          type: "doc",
          id: "getting-started/first-time-login-access",
          label: "First-Time Login & Access"
        },
        {
          type: "doc",
          id: "getting-started/organization-hierarchy-setup",
          label: "Organization & Hierarchy Setup"
        },
        {
          type: "doc",
          id: "getting-started/user-management-setup",
          label: "User Management Setup"
        },
        {
          type: "doc",
          id: "getting-started/quick-start-checklist",
          label: "Quick Start Checklist"
        }
      ]
    },
    {
      type: "category",
      label: "📱 Devices",
      collapsible: true,
      collapsed: false,
      link: {
        type: "generated-index",
        description: "Device configuration guides for all supported devices",
        slug: "/devices"
      },
      items: [
        {
          type: "doc",
          id: "devices/add-a-device-to-gcxone",
          label: "Add a Device to GCXONE"
        },
        {
          type: "doc",
          id: "devices/hikproconnect-troubleshoot",
          label: "Hik-ProConnect Device"
        },
        {
          type: "doc",
          id: "devices/hanwha-device-configuration",
          label: "Hanwha Device"
        },
        {
          type: "doc",
          id: "devices/axxon",
          label: "Axxon"
        },
        {
          type: "doc",
          id: "devices/ajax",
          label: "Ajax"
        },
        {
          type: "doc",
          id: "devices/axis-camera-station",
          label: "Axis Camera Station"
        },
        {
          type: "doc",
          id: "devices/axis-communications-family-integration-guide",
          label: "Axis Communications Family Integration Guide"
        },
        {
          type: "doc",
          id: "devices/axis-ip-camera",
          label: "Axis IP Camera"
        },
        {
          type: "doc",
          id: "devices/camect",
          label: "Camect Configuration Guide"
        },
        {
          type: "doc",
          id: "devices/dahua",
          label: "Dahua"
        },
        {
          type: "doc",
          id: "devices/dahua-cloud-arc",
          label: "Dahua Cloud ARC"
        },
        {
          type: "doc",
          id: "devices/eagle-eye",
          label: "Eagle Eye"
        },
        {
          type: "doc",
          id: "devices/genesis-audio",
          label: "GENESIS AUDIO"
        },
        {
          type: "doc",
          id: "devices/hikvision",
          label: "Hikvision"
        },
        {
          type: "doc",
          id: "devices/milestone-gcx-one",
          label: "Milestone GCX-ONE"
        },
        {
          type: "doc",
          id: "devices/senstar",
          label: "SenStar"
        },
        {
          type: "doc",
          id: "devices/victron",
          label: "Victron"
        }
      ]
    },
    {
      type: "category",
      label: "⚡ Features",
      collapsible: true,
      collapsed: false,
      link: {
        type: "generated-index",
        description: "Feature guides and configuration",
        slug: "/features"
      },
      items: [
        {
          type: "doc",
          id: "features/platform/feature-list",
          label: "Platform Feature List"
        },
        {
          type: "doc",
          id: "features/ai-automation/overview",
          label: "AI Analytics Overview"
        },
        {
          type: "doc",
          id: "features/ai-automation/genie-ai-assistant",
          label: "Genie AI Assistant"
        },
        {
          type: "doc",
          id: "features/system-monitoring/towerguard",
          label: "TowerGuard"
        },
        {
          type: "doc",
          id: "features/video-monitoring/live-view/overview",
          label: "Live View Overview"
        },
        {
          type: "doc",
          id: "features/video-monitoring/live-view/troubleshooting",
          label: "Live View Troubleshooting"
        },
        {
          type: "doc",
          id: "features/video-monitoring/playback/overview",
          label: "Playback Overview"
        },
        {
          type: "doc",
          id: "features/video-monitoring/playback/troubleshooting",
          label: "Playback Troubleshooting"
        },
        {
          type: "doc",
          id: "features/video-monitoring/video-streaming/overview",
          label: "Video Streaming Overview"
        },
        {
          type: "doc",
          id: "features/video-monitoring/video-streaming/troubleshooting",
          label: "Video Streaming Troubleshooting"
        },
        {
          type: "doc",
          id: "features/video-monitoring/video-streaming/configuration",
          label: "Video Streaming Configuration"
        },
        {
          type: "doc",
          id: "features/video-monitoring/ptz-control/overview",
          label: "PTZ Control Overview"
        },
        {
          type: "doc",
          id: "features/video-monitoring/ptz-control/configuration",
          label: "PTZ Control Configuration"
        },
        {
          type: "doc",
          id: "features/video-monitoring/event-clips/overview",
          label: "Event Clips Overview"
        },
        {
          type: "doc",
          id: "features/operational-modes/local-mode/overview",
          label: "Local Mode Overview"
        },
        {
          type: "doc",
          id: "features/operational-modes/local-mode/configuration",
          label: "Local Mode Configuration"
        },
        {
          type: "doc",
          id: "features/operational-modes/audio-routing-conference-mode",
          label: "Audio Routing & Conference Mode"
        },
        {
          type: "doc",
          id: "features/platform/marketplace",
          label: "Marketplace"
        }
      ]
    },
    {
      type: "category",
      label: "Installer Guide",
      collapsible: true,
      collapsed: false,
      link: {
        type: "generated-index",
        description: "Installation and deployment procedures",
        slug: "/installer-guide"
      },
      items: [
        {
          type: "doc",
          id: "installer-guide/device-installation",
          label: "Device Installation"
        },
        {
          type: "doc",
          id: "installer-guide/device-registration",
          label: "Device Registration"
        },
        {
          type: "doc",
          id: "installer-guide/environmental",
          label: "Environmental"
        },
        {
          type: "doc",
          id: "installer-guide/installation-overview",
          label: "Installation Overview"
        },
        {
          type: "doc",
          id: "installer-guide/maintenance-schedule",
          label: "Maintenance Schedule"
        },
        {
          type: "doc",
          id: "installer-guide/network-setup",
          label: "Network Setup"
        },
        {
          type: "doc",
          id: "installer-guide/post-installation",
          label: "Post Installation"
        },
        {
          type: "doc",
          id: "installer-guide/troubleshooting",
          label: "Troubleshooting"
        },
        {
          type: "doc",
          id: "installer-guide/bandwidth-requirements",
          label: "Bandwidth Requirements"
        },
        {
          type: "doc",
          id: "installer-guide/firewall-configuration",
          label: "Firewall Configuration"
        },
        {
          type: "doc",
          id: "installer-guide/ip-whitelisting",
          label: "IP Whitelisting"
        }
      ]
    },
    {
      type: "category",
      label: "Platform Fundamentals",
      collapsible: true,
      collapsed: false,
      link: {
        type: "generated-index",
        description: "Core platform architecture and concepts",
        slug: "/platform-fundamentals"
      },
      items: [
        {
          type: "doc",
          id: "platform-fundamentals/cloud-architecture",
          label: "Cloud Architecture"
        },
        {
          type: "doc",
          id: "platform-fundamentals/hierarchy-model",
          label: "Tenant-Customer-Site-Device Model"
        },
        {
          type: "doc",
          id: "platform-fundamentals/what-is-evalink-talos",
          label: "What is Evalink Talos?"
        },
        {
          type: "doc",
          id: "platform-fundamentals/getting-to-know-talos",
          label: "Getting to Know Talos"
        },
        {
          type: "doc",
          id: "platform-fundamentals/gcxone-talos-interaction",
          label: "GCXONE & Talos Interaction"
        },
        {
          type: "doc",
          id: "platform-fundamentals/talos-workflows",
          label: "Talos Workflows"
        },
        {
          type: "doc",
          id: "platform-fundamentals/event-processing",
          label: "Event Processing"
        },
        {
          type: "doc",
          id: "platform-fundamentals/alarm-flow",
          label: "Alarm Flow"
        },
        {
          type: "doc",
          id: "platform-fundamentals/site-synchronization",
          label: "Site Synchronization"
        },
        {
          type: "doc",
          id: "platform-fundamentals/roles-permissions",
          label: "Roles & Permissions"
        },
        {
          type: "doc",
          id: "platform-fundamentals/talos-user-management",
          label: "Talos User Management"
        },
        {
          type: "doc",
          id: "platform-fundamentals/inviting-users",
          label: "Inviting Users"
        },
        {
          type: "doc",
          id: "platform-fundamentals/managing-users",
          label: "Managing Users"
        },
        {
          type: "doc",
          id: "platform-fundamentals/troubleshooting-central",
          label: "Troubleshooting Central"
        },
        {
          type: "doc",
          id: "platform-fundamentals/two-factor-authentication",
          label: "Two-Factor Authentication"
        }
      ]
    },
    {
      type: "category",
      label: "Reporting",
      collapsible: true,
      collapsed: false,
      link: {
        type: "generated-index",
        description: "Reporting setup and usage",
        slug: "/reporting"
      },
      items: [
        {
          type: "doc",
          id: "reporting/report-sharing",
          label: "Report Sharing"
        },
        {
          type: "doc",
          id: "reporting/report-troubleshooting",
          label: "Report Troubleshooting"
        },
        {
          type: "doc",
          id: "reporting/reporting-overview",
          label: "Reporting Overview"
        },
        {
          type: "doc",
          id: "reporting/scheduled-reports",
          label: "Scheduled Reports"
        },
        {
          type: "doc",
          id: "reporting/standard-reports",
          label: "Standard Reports"
        }
      ]
    },
    {
      type: "category",
      label: "Support",
      collapsible: true,
      collapsed: false,
      link: {
        type: "generated-index",
        description: "Support and contact information",
        slug: "/support"
      },
      items: [
        {
          type: "doc",
          id: "support/contact",
          label: "Contact Support"
        }
      ]
    },
    {
      type: "category",
      label: "📚 Knowledge Base",
      collapsible: true,
      collapsed: false,
      link: {
        type: "generated-index",
        description: "Reference documentation, FAQs, glossary, and compliance information",
        slug: "/knowledge-base"
      },
      items: [
        {
          type: "doc",
          id: "knowledge-base/compliance",
          label: "Compliance"
        },
        {
          type: "doc",
          id: "knowledge-base/image-video-display-issues",
          label: "Image & Video Display Issues"
        },
        {
          type: "doc",
          id: "knowledge-base/integration-guides",
          label: "Integration Guides"
        },
        {
          type: "doc",
          id: "knowledge-base/network-requirements",
          label: "Network Requirements"
        },
        {
          type: "doc",
          id: "knowledge-base/quick-reference",
          label: "Quick Reference"
        },
        {
          type: "doc",
          id: "knowledge-base/data-privacy",
          label: "Data Privacy"
        },
        {
          type: "doc",
          id: "knowledge-base/faq",
          label: "FAQ"
        },
        {
          type: "doc",
          id: "knowledge-base/glossary",
          label: "Glossary of Terms"
        },
        {
          type: "doc",
          id: "knowledge-base/browser-errors",
          label: "Browser Errors"
        },
        {
          type: "doc",
          id: "knowledge-base/migration-guides",
          label: "Migration Guides"
        }
      ]
    },
    {
      type: "category",
      label: "Uncategorized",
      collapsible: true,
      collapsed: false,
      link: {
        type: "generated-index",
        description: "Docs automatically included in production sidebar without explicit sidebarCategory references.",
        slug: "/uncategorized"
      },
      items: [
        {
          type: "doc",
          id: "api-overview",
          label: "API Overview"
        },
        {
          type: "doc",
          id: "api-graphql",
          label: "GraphQL API"
        },
        {
          type: "doc",
          id: "quick-start-guide",
          label: "Quick Start Guide"
        },
        {
          type: "doc",
          id: "api-rest",
          label: "REST API Reference"
        },
        {
          type: "doc",
          id: "api-sdks",
          label: "SDKs & Libraries"
        },
        {
          type: "doc",
          id: "api-webhooks",
          label: "Webhooks"
        },
        {
          type: "doc",
          id: "platform-architecture-overview",
          label: "Platform Architecture Overview"
        },
        {
          type: "doc",
          id: "index",
          label: "Documentation Home"
        }
      ]
    }
  ],
};

export default sidebars;
