/**
 * Auto-generated sidebar configuration from Sanity.
 * This file is generated by scripts/generate-sidebar-from-sanity.js
 * DO NOT EDIT MANUALLY - changes will be overwritten.
 */
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  sanityDocsSidebar: [
    {
      type: "doc",
      id: "index",
      label: "Documentation Home"
    },
    {
      type: "category",
      label: "Devices",
      collapsible: true,
      collapsed: false,
      link: {
        type: "generated-index",
        slug: "/devices"
      },
      items: [
        {
          type: "doc",
          id: "devices/add-a-device-to-gcxone",
          label: "Add a Device to GCXONE"
        },
        {
          type: "doc",
          id: "devices/hikproconnect-troubleshoot",
          label: "Hik-ProConnect Device"
        },
        {
          type: "doc",
          id: "devices/hanwha-device-configuration",
          label: "Hanwha Device"
        },
        {
          type: "doc",
          id: "devices/axxon",
          label: "Axxon"
        },
        {
          type: "doc",
          id: "devices/ajax",
          label: "AJAX"
        },
        {
          type: "doc",
          id: "devices/axis-ip-camera",
          label: "Axis IP Camera"
        },
        {
          type: "doc",
          id: "devices/axis-camera-station",
          label: "Axis Camera Station"
        },
        {
          type: "doc",
          id: "devices/axis-communications-family-integration-guide",
          label: "Axis Communications Family Integration Guide"
        },
        {
          type: "doc",
          id: "devices/genesis-audio",
          label: "Genesis Audio"
        },
        {
          type: "doc",
          id: "devices/dahua-cloud-arc",
          label: "Dahua Cloud ARC"
        },
        {
          type: "doc",
          id: "devices/camect",
          label: "Camect Configuration Guide"
        },
        {
          type: "doc",
          id: "devices/dahua",
          label: "Dahua"
        },
        {
          type: "doc",
          id: "devices/eagle-eye",
          label: "Eagle Eye"
        },
        {
          type: "doc",
          id: "devices/hikvision",
          label: "Hikvision"
        },
        {
          type: "doc",
          id: "devices/milestone-gcx-one",
          label: "Milestone GCX-ONE"
        },
        {
          type: "doc",
          id: "devices/teltonika",
          label: "Teltonika"
        },
        {
          type: "doc",
          id: "devices/victron",
          label: "Victron"
        },
        {
          type: "doc",
          id: "devices/efoy-fuel-cell",
          label: "EFOY Fuel Cell"
        },
        {
          type: "doc",
          id: "devices/geutebrck",
          label: "Geutebrück"
        },
        {
          type: "doc",
          id: "devices/senstar",
          label: "SenStar"
        }
      ]
    },
    {
      type: "category",
      label: "Features",
      collapsible: true,
      collapsed: false,
      link: {
        type: "generated-index",
        slug: "/features"
      },
      items: [
        {
          type: "doc",
          id: "features/platform/feature-list",
          label: "Platform Feature List"
        },
        {
          type: "doc",
          id: "features/video-monitoring/live-view/overview",
          label: "Live View Overview"
        },
        {
          type: "doc",
          id: "features/video-monitoring/live-view/troubleshooting",
          label: "Live View Troubleshooting"
        },
        {
          type: "doc",
          id: "features/video-monitoring/video-streaming/overview",
          label: "Video Streaming Overview"
        },
        {
          type: "doc",
          id: "features/video-monitoring/video-streaming/configuration",
          label: "Video Streaming Configuration"
        },
        {
          type: "doc",
          id: "features/video-monitoring/video-streaming/troubleshooting",
          label: "Video Streaming Troubleshooting"
        },
        {
          type: "doc",
          id: "features/operational-modes/local-mode/overview",
          label: "Local Mode Overview"
        },
        {
          type: "doc",
          id: "features/operational-modes/local-mode/configuration",
          label: "Local Mode Configuration"
        },
        {
          type: "doc",
          id: "features/video-monitoring/ptz-control/overview",
          label: "PTZ Control Overview"
        },
        {
          type: "doc",
          id: "features/video-monitoring/ptz-control/configuration",
          label: "PTZ Control Configuration"
        },
        {
          type: "doc",
          id: "features/operational-modes/audio-routing-conference-mode",
          label: "Audio Routing & Conference Mode"
        },
        {
          type: "doc",
          id: "features/video-monitoring/playback/overview",
          label: "Playback Overview"
        },
        {
          type: "doc",
          id: "features/video-monitoring/playback/troubleshooting",
          label: "Playback Troubleshooting"
        },
        {
          type: "doc",
          id: "features/video-monitoring/event-clips/overview",
          label: "Event Clips Overview"
        },
        {
          type: "doc",
          id: "features/ai-automation/overview",
          label: "AI Analytics Overview"
        },
        {
          type: "doc",
          id: "features/nova99x",
          label: "Nova99x"
        },
        {
          type: "doc",
          id: "features/auto-stream-new",
          label: "Auto Stream"
        },
        {
          type: "doc",
          id: "features/zenmode",
          label: "ZenMode"
        },
        {
          type: "doc",
          id: "features/alarm-management-system",
          label: "Alarm Management System"
        },
        {
          type: "doc",
          id: "features/healthcheck",
          label: "HealthCheck"
        },
        {
          type: "doc",
          id: "features/maps",
          label: "Maps"
        },
        {
          type: "doc",
          id: "features/system-monitoring/towerguard",
          label: "TowerGuard"
        },
        {
          type: "doc",
          id: "features/platform/marketplace",
          label: "Marketplace"
        },
        {
          type: "doc",
          id: "features/bulkimport",
          label: "BulkImport"
        },
        {
          type: "doc",
          id: "features/customview",
          label: "CustomView"
        },
        {
          type: "doc",
          id: "features/universal-search",
          label: "Universal Search"
        },
        {
          type: "doc",
          id: "features/timesync",
          label: "TimeSync"
        },
        {
          type: "doc",
          id: "features/pulseview",
          label: "PulseView"
        },
        {
          type: "doc",
          id: "features/ai-automation/genie-ai-assistant",
          label: "Genie AI Assistant"
        }
      ]
    },
    {
      type: "category",
      label: "Reporting",
      collapsible: true,
      collapsed: false,
      link: {
        type: "generated-index",
        slug: "/reporting"
      },
      items: [
        {
          type: "doc",
          id: "reporting/report-sharing",
          label: "Report Sharing"
        },
        {
          type: "doc",
          id: "reporting/report-troubleshooting",
          label: "Report Troubleshooting"
        },
        {
          type: "doc",
          id: "reporting/reporting-overview",
          label: "Reporting Overview"
        },
        {
          type: "doc",
          id: "reporting/standard-reports",
          label: "Standard Reports"
        }
      ]
    },
    {
      type: "category",
      label: "Support",
      collapsible: true,
      collapsed: false,
      link: {
        type: "generated-index",
        slug: "/support"
      },
      items: [
        {
          type: "doc",
          id: "support/contact",
          label: "Contact Support"
        }
      ]
    }
  ],
};

export default sidebars;
