/**
 * Auto-generated sidebar configuration from Sanity.
 * This file is generated by scripts/generate-sidebars-from-sanity.js
 * DO NOT EDIT MANUALLY - changes will be overwritten.
 */
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  managerSidebar: [
    {
      type: "doc",
      id: "index",
      label: "Home"
    }
  ],
};

export default sidebars;
