/**
 * Auto-generated sidebar configuration from Sanity.
 * This file is generated by scripts/generate-sidebars-from-sanity.js
 * DO NOT EDIT MANUALLY - changes will be overwritten.
 */
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  sanityDocsSidebar: [
    {
      type: "doc",
      id: "index",
      label: "Documentation Home"
    },
    {
      type: "category",
      label: "Getting Started",
      collapsible: true,
      collapsed: false,
      link: {
        type: "generated-index",
        description: "Getting Started",
        slug: "/getting-started"
      },
      items: [
        {
          type: "doc",
          id: "getting-started/what-is-gcxone",
          label: "What is GCXOne"
        },
        {
          type: "doc",
          id: "getting-started/pre-deployment-requirements",
          label: "Pre-Deployment Requirements"
        },
        {
          type: "doc",
          id: "getting-started/first-time-login-access",
          label: "First-Time Login & Access"
        },
        {
          type: "doc",
          id: "getting-started/organization-hierarchy-setup",
          label: "Organization & Hierarchy Setup"
        },
        {
          type: "doc",
          id: "getting-started/user-management-setup",
          label: "User Management Setup"
        },
        {
          type: "doc",
          id: "getting-started/quick-start-checklist",
          label: "Quick Start Checklist"
        }
      ]
    },
    {
      type: "category",
      label: "_archived_platform_fundamentals_old",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "platform-fundamentals/talos-workflows",
          label: "Talos Workflows"
        }
      ]
    },
    {
      type: "category",
      label: "Breakthroughs",
      collapsible: true,
      collapsed: false,
      link: {
        type: "generated-index",
        description: "Advanced Features and Innovations",
        slug: "/breakthroughs"
      },
      items: [
        {
          type: "doc",
          id: "features/nova99x",
          label: "NOVA99x"
        },
        {
          type: "doc",
          id: "features/zenmode",
          label: "ZenMode"
        },
        {
          type: "doc",
          id: "features/healthcheck",
          label: "HealthCheck"
        },
        {
          type: "doc",
          id: "features/system-monitoring/towerguard",
          label: "TowerGuard"
        },
        {
          type: "doc",
          id: "features/ai-automation/genie-ai-assistant",
          label: "Genie AI Assistant"
        },
        {
          type: "doc",
          id: "features/bulkimport",
          label: "BulkImport"
        },
        {
          type: "doc",
          id: "features/customview",
          label: "CustomView"
        },
        {
          type: "doc",
          id: "features/pulseview",
          label: "PulseView"
        },
        {
          type: "doc",
          id: "features/timesync",
          label: "TimeSync"
        },
        {
          type: "doc",
          id: "features/platform/marketplace",
          label: "Marketplace"
        }
      ]
    },
    {
      type: "category",
      label: "Installer Guide",
      collapsible: true,
      collapsed: false,
      link: {
        type: "generated-index",
        description: "Installation and setup procedures",
        slug: "/installer-guide"
      },
      items: [
        {
          type: "doc",
          id: "installer-guide/environmental",
          label: "Environmental"
        },
        {
          type: "doc",
          id: "installer-guide/network-setup",
          label: "Network Setup"
        },
        {
          type: "doc",
          id: "installer-guide/troubleshooting",
          label: "Troubleshooting"
        },
        {
          type: "doc",
          id: "installer-guide/installation-overview",
          label: "Installation Overview"
        },
        {
          type: "doc",
          id: "installer-guide/firewall-configuration",
          label: "Firewall Configuration"
        },
        {
          type: "doc",
          id: "installer-guide/ip-whitelisting",
          label: "IP Whitelisting"
        },
        {
          type: "doc",
          id: "installer-guide/bandwidth-requirements",
          label: "Bandwidth Requirements"
        },
        {
          type: "doc",
          id: "installer-guide/device-installation",
          label: "Device Installation"
        },
        {
          type: "doc",
          id: "installer-guide/device-registration",
          label: "Device Registration"
        },
        {
          type: "doc",
          id: "installer-guide/post-installation",
          label: "Post Installation"
        }
      ]
    },
    {
      type: "category",
      label: "Operator Guide",
      collapsible: true,
      collapsed: false,
      link: {
        type: "generated-index",
        description: "Daily operations and usage",
        slug: "/operator-guide"
      },
      items: [
        {
          type: "doc",
          id: "operator-guide/site-management",
          label: "Site Management"
        },
        {
          type: "doc",
          id: "operator-guide/escalation-procedures",
          label: "Escalation Procedures"
        }
      ]
    },
    {
      type: "category",
      label: "Reporting",
      collapsible: true,
      collapsed: false,
      link: {
        type: "generated-index",
        description: "System reports and analytics",
        slug: "/reporting"
      },
      items: [
        {
          type: "doc",
          id: "reporting/report-sharing",
          label: "Report Sharing"
        },
        {
          type: "doc",
          id: "reporting/report-troubleshooting",
          label: "Report Troubleshooting"
        },
        {
          type: "doc",
          id: "reporting/standard-reports",
          label: "Standard Reports"
        },
        {
          type: "doc",
          id: "reporting/reporting-overview",
          label: "Reporting Overview"
        }
      ]
    },
    {
      type: "category",
      label: "Support",
      collapsible: true,
      collapsed: false,
      link: {
        type: "generated-index",
        description: "Support and contact information",
        slug: "/support"
      },
      items: [
        {
          type: "doc",
          id: "support/contact",
          label: "Contact Support"
        }
      ]
    },
    {
      type: "category",
      label: "Api Graphql",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "api-graphql",
          label: "GraphQL API"
        }
      ]
    },
    {
      type: "category",
      label: "Api Overview",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "api-overview",
          label: "API Overview"
        }
      ]
    },
    {
      type: "category",
      label: "Api Rest",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "api-rest",
          label: "REST API Reference"
        }
      ]
    },
    {
      type: "category",
      label: "Api Sdks",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "api-sdks",
          label: "SDKs & Libraries"
        }
      ]
    },
    {
      type: "category",
      label: "Api Webhooks",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "api-webhooks",
          label: "Webhooks"
        }
      ]
    },
    {
      type: "category",
      label: "Features",
      collapsible: true,
      collapsed: false,
      link: {
        type: "generated-index",
        description: "Auto-created from existing doc slugs (features)",
        slug: "/features"
      },
      items: [
        {
          type: "doc",
          id: "features/video-monitoring/multi-monitor",
          label: "Multi Monitor"
        },
        {
          type: "doc",
          id: "features/video-monitoring/edit-properties",
          label: "Edit Properties"
        },
        {
          type: "doc",
          id: "features/alarms-ai/alarm-mapping",
          label: "Alarm Mapping"
        },
        {
          type: "doc",
          id: "features/alarms-ai/workflows",
          label: "Workflows"
        },
        {
          type: "doc",
          id: "features/alarms-ai/dc09",
          label: "DC09"
        },
        {
          type: "doc",
          id: "features/alarms-ai/standard-vs-smart-alarm",
          label: "Standard Motion Alarm vs Smart Alarm"
        },
        {
          type: "doc",
          id: "features/audio/speaker-on-help-desk",
          label: "Speaker on Help Desk"
        },
        {
          type: "doc",
          id: "features/audio/audio-io",
          label: "Audio I/O"
        },
        {
          type: "doc",
          id: "features/operational-tools/analytics",
          label: "Analytics"
        },
        {
          type: "doc",
          id: "features/operational-tools/tags",
          label: "Tags"
        },
        {
          type: "doc",
          id: "features/operational-tools/audit",
          label: "Audit"
        }
      ]
    },
    {
      type: "category",
      label: "Platform Architecture Overview",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "platform-architecture-overview",
          label: "Platform Architecture Overview"
        }
      ]
    },
    {
      type: "category",
      label: "Quick Start Guide",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "quick-start-guide",
          label: "Quick Start Guide"
        }
      ]
    },
    {
      type: "category",
      label: "Platform Fundamentals",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "platform-fundamentals/cloud-architecture",
          label: "Cloud Architecture"
        },
        {
          type: "doc",
          id: "platform-fundamentals/hierarchy-model",
          label: "Tenant-Customer-Site-Device Model"
        },
        {
          type: "doc",
          id: "platform-fundamentals/what-is-evalink-talos",
          label: "What is Evalink Talos?"
        },
        {
          type: "doc",
          id: "platform-fundamentals/getting-to-know-talos",
          label: "Getting to Know Talos"
        },
        {
          type: "doc",
          id: "platform-fundamentals/gcxone-talos-interaction",
          label: "GCXONE & Talos Interaction"
        },
        {
          type: "doc",
          id: "platform-fundamentals/event-processing",
          label: "Event Processing"
        },
        {
          type: "doc",
          id: "platform-fundamentals/alarm-flow",
          label: "Alarm Flow"
        },
        {
          type: "doc",
          id: "platform-fundamentals/site-synchronization",
          label: "Site Synchronization"
        },
        {
          type: "doc",
          id: "platform-fundamentals/roles-permissions",
          label: "Roles & Permissions"
        },
        {
          type: "doc",
          id: "platform-fundamentals/privilege-deep-dive",
          label: "Privilege Deep Dive"
        },
        {
          type: "doc",
          id: "platform-fundamentals/talos-user-management",
          label: "Talos User Management"
        },
        {
          type: "doc",
          id: "platform-fundamentals/inviting-users",
          label: "Inviting Users"
        },
        {
          type: "doc",
          id: "platform-fundamentals/managing-users",
          label: "Managing Users"
        }
      ]
    },
    {
      type: "category",
      label: "Devices & Integrations",
      collapsible: true,
      collapsed: false,
      link: {
        type: "generated-index",
        description: "Device configuration guides organized by category",
        slug: "/devices-integrations"
      },
      items: [
        {
          type: "doc",
          id: "devices/add-a-device-to-gcxone",
          label: "Add a Device to GCXONE"
        },
        {
          type: "doc",
          id: "devices/hanwha-device-configuration",
          label: "Hanwha Device"
        },
        {
          type: "doc",
          id: "devices/eagle-eye",
          label: "Eagle Eye"
        },
        {
          type: "doc",
          id: "devices/axis-ip-camera",
          label: "Axis IP Camera"
        },
        {
          type: "doc",
          id: "devices/Cloud-VMS/hikproconnect-troubleshoot",
          label: "Hik-ProConnect Device"
        },
        {
          type: "doc",
          id: "devices/dahua-cloud-arc",
          label: "Dahua Cloud ARC"
        },
        {
          type: "doc",
          id: "devices/axis-camera-station",
          label: "Axis Camera Station"
        },
        {
          type: "doc",
          id: "devices/dahua",
          label: "Dahua"
        },
        {
          type: "doc",
          id: "genesis-audio",
          label: "Genesis Audio"
        },
        {
          type: "doc",
          id: "devices/ajax",
          label: "AJAX"
        },
        {
          type: "doc",
          id: "devices/teltonika",
          label: "Teltonika"
        },
        {
          type: "doc",
          id: "devices/efoy-fuel-cell",
          label: "EFOY Fuel Cell"
        },
        {
          type: "doc",
          id: "devices/senstar",
          label: "SenStar"
        },
        {
          type: "doc",
          id: "devices/victron",
          label: "Victron"
        },
        {
          type: "doc",
          id: "devices/camect",
          label: "Camect Configuration Guide"
        },
        {
          type: "doc",
          id: "devices/milestone-gcx-one",
          label: "Milestone GCX-ONE"
        },
        {
          type: "doc",
          id: "devices/axxon",
          label: "Axxon"
        },
        {
          type: "doc",
          id: "devices/axis-communications-family-integration-guide",
          label: "Axis Communications Family Integration Guide"
        },
        {
          type: "doc",
          id: "devices/geutebrck",
          label: "Geutebrck"
        },
        {
          type: "doc",
          id: "devices/hikvision",
          label: "Hikvision"
        }
      ]
    },
    {
      type: "category",
      label: "Platform Features",
      collapsible: true,
      collapsed: false,
      link: {
        type: "generated-index",
        description: "Video monitoring, alarms, audio, and operational tools",
        slug: "/platform-features"
      },
      items: [
        {
          type: "doc",
          id: "features/platform/feature-list",
          label: "Platform Feature List"
        },
        {
          type: "doc",
          id: "features/alarm-management-system",
          label: "Alarm Management System"
        },
        {
          type: "doc",
          id: "features/video-monitoring/live-view/overview",
          label: "Live View Overview"
        },
        {
          type: "doc",
          id: "features/video-monitoring/live-view/troubleshooting",
          label: "Live View Troubleshooting"
        },
        {
          type: "doc",
          id: "features/live-view-advanced-troubleshooting",
          label: "Live View Advanced Troubleshooting"
        },
        {
          type: "doc",
          id: "features/video-monitoring/video-streaming/overview",
          label: "Video Streaming Overview"
        },
        {
          type: "doc",
          id: "features/video-monitoring/video-streaming/configuration",
          label: "Video Streaming Configuration"
        },
        {
          type: "doc",
          id: "features/video-monitoring/video-streaming/troubleshooting",
          label: "Video Streaming Troubleshooting"
        },
        {
          type: "doc",
          id: "features/video-monitoring/playback/overview",
          label: "Playback Overview"
        },
        {
          type: "doc",
          id: "features/video-monitoring/playback/troubleshooting",
          label: "Playback Troubleshooting"
        },
        {
          type: "doc",
          id: "features/video-monitoring/ptz-control/overview",
          label: "PTZ Control Overview"
        },
        {
          type: "doc",
          id: "features/video-monitoring/ptz-control/configuration",
          label: "PTZ Control Configuration"
        },
        {
          type: "doc",
          id: "features/video-monitoring/event-clips/overview",
          label: "Event Clips Overview"
        },
        {
          type: "doc",
          id: "features/ai-automation/overview",
          label: "AI Analytics Overview"
        },
        {
          type: "doc",
          id: "features/auto-stream-new",
          label: "Auto Stream"
        },
        {
          type: "doc",
          id: "features/operational-modes/audio-routing-conference-mode",
          label: "Audio Routing & Conference Mode"
        },
        {
          type: "doc",
          id: "features/maps",
          label: "Maps"
        },
        {
          type: "doc",
          id: "features/universal-search",
          label: "Universal Search"
        },
        {
          type: "doc",
          id: "features/operational-modes/local-mode/overview",
          label: "Local Mode Overview"
        },
        {
          type: "doc",
          id: "features/operational-modes/local-mode/configuration",
          label: "Local Mode Configuration"
        }
      ]
    },
    {
      type: "category",
      label: "Datasheets & Specs",
      collapsible: true,
      collapsed: false,
      link: {
        type: "generated-index",
        description: "Device datasheets, integration specs, and compliance",
        slug: "/datasheets-specs"
      },
      items: [
        {
          type: "doc",
          id: "knowledge-base/image-video-display-issues",
          label: "Image & Video Display Issues"
        },
        {
          type: "doc",
          id: "knowledge-base/browser-errors",
          label: "Browser Errors"
        },
        {
          type: "doc",
          id: "knowledge-base/integration-guides",
          label: "Integration Guides"
        },
        {
          type: "doc",
          id: "knowledge-base/migration-guides",
          label: "Migration Guides"
        },
        {
          type: "doc",
          id: "knowledge-base/network-requirements",
          label: "Network Requirements"
        },
        {
          type: "doc",
          id: "knowledge-base/quick-reference",
          label: "Quick Reference"
        },
        {
          type: "doc",
          id: "knowledge-base/compliance",
          label: "Compliance"
        },
        {
          type: "doc",
          id: "knowledge-base/data-privacy",
          label: "Data Privacy"
        },
        {
          type: "doc",
          id: "knowledge-base/glossary",
          label: "Glossary of Terms"
        },
        {
          type: "doc",
          id: "knowledge-base/faq",
          label: "FAQ"
        }
      ]
    },
    {
      type: "category",
      label: "Uncategorized",
      collapsible: true,
      collapsed: false,
      link: {
        type: "generated-index",
        description: "Docs automatically included in production sidebar without explicit sidebarCategory references.",
        slug: "/uncategorized"
      },
      items: [
        {
          type: "doc",
          id: "index",
          label: "Documentation Home"
        }
      ]
    }
  ],
};

export default sidebars;
