// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokRichtext } from '../storyblok.d.ts';
export interface DocPage {
  title?: string;
  body?: StoryblokRichtext;
  description?: string;
  component: "doc_page";
  _uid: string;
  [k: string]: unknown;
}

export interface Feature {
  name?: string;
  component: "feature";
  _uid: string;
  [k: string]: unknown;
}

export interface Grid {
  columns?: (DocPage | Feature | Grid | Page | Teaser)[];
  component: "grid";
  _uid: string;
  [k: string]: unknown;
}

export interface Page {
  title?: string;
  body: string;
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface Teaser {
  headline?: string;
  component: "teaser";
  _uid: string;
  [k: string]: unknown;
}

export type ContentType = DocPage | Page;
