import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: 'Getting Started',
      link: { type: 'generated-index', description: 'Get started with NXGEN GCXONE platform' },
      items: [
        'getting-started/what-is-nxgen-GCXONE',
        'getting-started/what-is-evalink-talos',
        'getting-started/GCXONE-talos-interaction',
        'getting-started/key-benefits',
        'getting-started/cloud-architecture',
        'getting-started/required-ports',
        'getting-started/ip-whitelisting',
        'getting-started/firewall-configuration',
        'getting-started/bandwidth-requirements',
        'getting-started/ntp-configuration',
        'getting-started/first-time-login',
        'getting-started/password-management',
        'getting-started/quick-start-checklist',
      ],
    },
    {
      type: 'category',
      label: 'Platform Fundamentals',
      link: { type: 'generated-index', description: 'Deep dive into GCXONE platform architecture' },
      items: [
        'platform-fundamentals/microservices-architecture',
        'platform-fundamentals/proxy-architecture',
        'platform-fundamentals/device-protocols',
        'platform-fundamentals/hierarchy-model',
        'platform-fundamentals/multi-tenant',
        'platform-fundamentals/alarm-flow',
        'platform-fundamentals/site-synchronization',
        'platform-fundamentals/event-processing',
        'platform-fundamentals/token-configuration',
        'platform-fundamentals/system-health-overview',
      ],
    },
    {
      type: 'category',
      label: 'Admin & Configuration',
      link: { type: 'generated-index', description: 'Administration and configuration guides' },
      items: [
        'admin-guide/dashboard-overview',
        'admin-guide/active-sites-widget',
        'admin-guide/alarm-volume-analytics',
        'admin-guide/device-health-status',
        'admin-guide/creating-customers',
        'admin-guide/creating-sites',
        'admin-guide/site-groups',
        'admin-guide/creating-users',
        'admin-guide/rbac',
        'admin-guide/permissions-matrix',
        'admin-guide/custom-properties-overview',
        'admin-guide/custom-property-hierarchy',
        'admin-guide/event-clip-configuration',
        'admin-guide/timezone-management',
      ],
    },
    {
      type: 'category',
      label: 'Devices',
      link: { type: 'generated-index', description: 'Device configuration guides for all supported devices' },
      items: [
        {
          type: 'category',
          label: 'General Onboarding',
          items: [
            'devices/general/onboarding-overview',
            'devices/general/discovery-methods',
            'devices/general/authentication',
            'devices/general/health-monitoring',
            'devices/general/troubleshooting-basics',
          ],
        },
        {
          type: 'category',
          label: 'ADPRO',
          items: [
            'devices/adpro/overview',
            'devices/adpro/admin-configuration',
            'devices/adpro/installer-configuration',
            'devices/adpro/operator-view',
            'devices/adpro/supported-features',
            'devices/adpro/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Hikvision',
          items: [
            'devices/hikvision/overview',
            'devices/hikvision/admin-configuration',
            'devices/hikvision/installer-configuration',
            'devices/hikvision/operator-view',
            'devices/hikvision/supported-features',
            'devices/hikvision/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Dahua',
          items: [
            'devices/dahua/overview',
            'devices/dahua/admin-configuration',
            'devices/dahua/dolynk-setup',
            'devices/dahua/installer-configuration',
            'devices/dahua/operator-view',
            'devices/dahua/supported-features',
            'devices/dahua/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Hanwha',
          items: [
            'devices/hanwha/overview',
            'devices/hanwha/admin-configuration',
            'devices/hanwha/installer-configuration',
            'devices/hanwha/operator-view',
            'devices/hanwha/supported-features',
            'devices/hanwha/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Milestone',
          items: [
            'devices/milestone/overview',
            'devices/milestone/admin-configuration',
            'devices/milestone/installer-configuration',
            'devices/milestone/operator-view',
            'devices/milestone/supported-features',
            'devices/milestone/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Axxon',
          items: [
            'devices/axxon/overview',
            'devices/axxon/admin-configuration',
            'devices/axxon/installer-configuration',
            'devices/axxon/operator-view',
            'devices/axxon/supported-features',
            'devices/axxon/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Camect',
          items: [
            'devices/camect/overview',
            'devices/camect/admin-configuration',
            'devices/camect/installer-configuration',
            'devices/camect/operator-view',
            'devices/camect/supported-features',
            'devices/camect/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Axis',
          items: [
            'devices/axis/overview',
            'devices/axis/admin-configuration',
            'devices/axis/installer-configuration',
            'devices/axis/operator-view',
            'devices/axis/supported-features',
            'devices/axis/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Heitel',
          items: [
            'devices/heitel/overview',
            'devices/heitel/admin-configuration',
            'devices/heitel/installer-configuration',
            'devices/heitel/operator-view',
            'devices/heitel/supported-features',
            'devices/heitel/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Reconeyez',
          items: [
            'devices/reconeyez/overview',
            'devices/reconeyez/admin-configuration',
            'devices/reconeyez/installer-configuration',
            'devices/reconeyez/operator-view',
            'devices/reconeyez/supported-features',
            'devices/reconeyez/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Teltonika',
          items: [
            'devices/teltonika/overview',
            'devices/teltonika/admin-configuration',
            'devices/teltonika/installer-configuration',
            'devices/teltonika/operator-view',
            'devices/teltonika/supported-features',
            'devices/teltonika/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'GCXONE Audio',
          items: [
            'devices/GCXONE-audio/overview',
            'devices/GCXONE-audio/admin-configuration',
            'devices/GCXONE-audio/installer-configuration',
            'devices/GCXONE-audio/operator-view',
            'devices/GCXONE-audio/supported-features',
            'devices/GCXONE-audio/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Avigilon',
          items: [
            'devices/avigilon/overview',
            'devices/avigilon/admin-configuration',
            'devices/avigilon/installer-configuration',
            'devices/avigilon/operator-view',
            'devices/avigilon/supported-features',
            'devices/avigilon/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'InnoVi',
          items: [
            'devices/innovi/overview',
            'devices/innovi/admin-configuration',
            'devices/innovi/installer-configuration',
            'devices/innovi/operator-view',
            'devices/innovi/supported-features',
            'devices/innovi/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Ajax',
          items: [
            'devices/ajax/overview',
          ],
        },
        {
          type: 'category',
          label: 'EagleEye',
          items: [
            'devices/eagleeye/overview',
          ],
        },
        {
          type: 'category',
          label: 'Ganz',
          items: [
            'devices/ganz/overview',
          ],
        },
        {
          type: 'category',
          label: 'Uniview',
          items: [
            'devices/uniview/overview',
          ],
        },
        {
          type: 'category',
          label: 'Generic Devices',
          items: [
            'devices/generic/onvif-integration',
            'devices/generic/rtsp-configuration',
            'devices/generic/limitations',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Features',
      link: { type: 'generated-index', description: 'Feature guides and configuration' },
      items: [
        {
          type: 'category',
          label: 'AI Analytics',
          items: [
            'features/ai-analytics/overview',
            'features/ai-analytics/configuration',
            'features/ai-analytics/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Video Streaming',
          items: [
            'features/video-streaming/overview',
            'features/video-streaming/configuration',
            'features/video-streaming/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'PTZ Control',
          items: [
            'features/ptz-control/overview',
            'features/ptz-control/configuration',
            'features/ptz-control/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Event Clips',
          items: [
            'features/event-clips/overview',
            'features/event-clips/configuration',
            'features/event-clips/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Playback',
          items: [
            'features/playback/overview',
            'features/playback/configuration',
            'features/playback/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Live View',
          items: [
            'features/live-view/overview',
            'features/live-view/configuration',
            'features/live-view/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Motion Detection',
          items: [
            'features/motion-detection/overview',
            'features/motion-detection/configuration',
            'features/motion-detection/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Line Crossing',
          items: [
            'features/line-crossing/overview',
            'features/line-crossing/configuration',
            'features/line-crossing/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Intrusion Detection',
          items: [
            'features/intrusion-detection/overview',
            'features/intrusion-detection/configuration',
            'features/intrusion-detection/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Face Detection',
          items: [
            'features/face-detection/overview',
            'features/face-detection/configuration',
            'features/face-detection/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'License Plate Recognition',
          items: [
            'features/license-plate/overview',
            'features/license-plate/configuration',
            'features/license-plate/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Audio Detection',
          items: [
            'features/audio-detection/overview',
            'features/audio-detection/configuration',
            'features/audio-detection/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Tamper Detection',
          items: [
            'features/tamper-detection/overview',
            'features/tamper-detection/configuration',
            'features/tamper-detection/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'People Counting',
          items: [
            'features/people-counting/overview',
            'features/people-counting/configuration',
            'features/people-counting/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Heat Mapping',
          items: [
            'features/heat-mapping/overview',
            'features/heat-mapping/configuration',
            'features/heat-mapping/troubleshooting',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Alarm Management (Talos)',
      link: { type: 'generated-index', description: 'Alarm management and monitoring with Talos' },
      items: [
        'alarm-management/talos-dashboard',
        'alarm-management/alarm-queue',
        'alarm-management/alarm-prioritization',
        'alarm-management/alarm-actions',
        'alarm-management/escalation-rules',
        'alarm-management/alarm-filtering',
        'alarm-management/alarm-history',
        'alarm-management/alarm-notifications',
        'alarm-management/alarm-routing',
        'alarm-management/alarm-metrics',
        'alarm-management/false-alarms',
        'alarm-management/alarm-verification',
        'alarm-management/multi-site-alarms',
        'alarm-management/alarm-sla',
        'alarm-management/alarm-integration',
        'alarm-management/alarm-reporting',
        'alarm-management/alarm-troubleshooting',
        'alarm-management/alarm-best-practices',
        'alarm-management/operator-training',
        'alarm-management/system-health',
      ],
    },
    {
      type: 'category',
      label: 'Reporting & Analytics',
      link: { type: 'generated-index', description: 'Reports and analytics tools' },
      items: [
        'reporting/reporting-overview',
        'reporting/standard-reports',
        'reporting/custom-reports',
        'reporting/scheduled-reports',
        'reporting/report-export',
        'reporting/device-activity',
        'reporting/alarm-statistics',
        'reporting/user-activity',
        'reporting/system-performance',
        'reporting/compliance-reports',
        'reporting/event-analytics',
        'reporting/trend-analysis',
        'reporting/dashboard-widgets',
        'reporting/report-sharing',
        'reporting/report-troubleshooting',
      ],
    },
    {
      type: 'category',
      label: 'Operator Guide',
      link: { type: 'generated-index', description: 'Guide for monitoring operators' },
      items: [
        'operator-guide/operator-dashboard',
        'operator-guide/handling-alarms',
        'operator-guide/live-video',
        'operator-guide/video-playback',
        'operator-guide/ptz-control',
        'operator-guide/event-clips',
        'operator-guide/site-navigation',
        'operator-guide/multi-site-monitoring',
        'operator-guide/response-procedures',
        'operator-guide/communication-tools',
        'operator-guide/shift-handover',
        'operator-guide/notes-annotations',
        'operator-guide/emergency-procedures',
        'operator-guide/performance-metrics',
        'operator-guide/best-practices',
        'operator-guide/shortcuts-tips',
        'operator-guide/troubleshooting',
        'operator-guide/training-guide',
      ],
    },
    {
      type: 'category',
      label: 'Installer Guide',
      link: { type: 'generated-index', description: 'Installation and setup guides' },
      items: [
        'installer-guide/installation-overview',
        'installer-guide/site-survey',
        'installer-guide/network-setup',
        'installer-guide/device-installation',
        'installer-guide/camera-positioning',
        'installer-guide/network-configuration',
        'installer-guide/device-registration',
        'installer-guide/testing-commissioning',
        'installer-guide/cable-management',
        'installer-guide/power-requirements',
        'installer-guide/environmental',
        'installer-guide/mounting-hardware',
        'installer-guide/bandwidth-planning',
        'installer-guide/storage-requirements',
        'installer-guide/redundancy-failover',
        'installer-guide/best-practices',
        'installer-guide/troubleshooting',
        'installer-guide/post-installation',
        'installer-guide/maintenance-schedule',
        'installer-guide/certification',
      ],
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      link: { type: 'generated-index', description: 'Troubleshooting guides and solutions' },
      items: [
        'troubleshooting/overview',
        'troubleshooting/connection-issues',
        'troubleshooting/video-streaming',
        'troubleshooting/login-problems',
        'troubleshooting/device-offline',
        'troubleshooting/alarm-not-received',
        'troubleshooting/video-quality',
        'troubleshooting/ptz-not-working',
        'troubleshooting/playback-issues',
        'troubleshooting/clips-missing',
        'troubleshooting/network-connectivity',
        'troubleshooting/firewall-issues',
        'troubleshooting/certificate-errors',
        'troubleshooting/performance-issues',
        'troubleshooting/browser-compatibility',
        'troubleshooting/mobile-app',
        'troubleshooting/audio-problems',
        'troubleshooting/time-sync',
        'troubleshooting/storage-issues',
        'troubleshooting/api-issues',
      ],
    },
    {
      type: 'category',
      label: 'Knowledge Base',
      link: { type: 'generated-index', description: 'Knowledge base and reference materials' },
      items: [
        'knowledge-base/faq',
        'knowledge-base/glossary',
        'knowledge-base/video-tutorials',
        'knowledge-base/quick-reference',
        'knowledge-base/system-requirements',
        'knowledge-base/browser-requirements',
        'knowledge-base/network-requirements',
        'knowledge-base/security-best-practices',
        'knowledge-base/backup-recovery',
        'knowledge-base/compliance',
        'knowledge-base/data-privacy',
        'knowledge-base/api-documentation',
        'knowledge-base/integration-guides',
        'knowledge-base/migration-guides',
        'knowledge-base/performance-optimization',
      ],
    },
    {
      type: 'category',
      label: 'Release Notes',
      link: { type: 'generated-index', description: 'Release notes and version history' },
      items: [
        'release-notes/latest',
        'release-notes/v3-0',
        'release-notes/v2-9',
        'release-notes/v2-8',
        'release-notes/v2-7',
        'release-notes/v2-6',
        'release-notes/deprecated',
        'release-notes/upgrade-guide',
        'release-notes/breaking-changes',
        'release-notes/roadmap',
      ],
    },
    {
      type: 'category',
      label: 'Support & Resources',
      link: { type: 'generated-index', description: 'Support and additional resources' },
      items: [
        'support/contact-support',
        'support/ticket-system',
        'support/support-sla',
        'support/training-resources',
        'support/certification',
        'support/community-forum',
        'support/partner-program',
        'support/professional-services',
        'support/system-status',
        'support/feedback',
      ],
    },
  ],
};

export default sidebars;
