// Utility to load sidebar config from sidebars.ts
// Since we can't directly import the TypeScript file, we'll parse it or use a simpler approach
export async function loadSidebarConfig(): Promise<any[]> {
  try {
    // Try to fetch from admin API if available
    const token = localStorage.getItem('admin_token');
    if (token) {
      try {
        const response = await fetch('http://localhost:3001/api/sidebar-config', {
          headers: { Authorization: `Bearer ${token}` },
        });
        if (response.ok) {
          return await response.json();
        }
      } catch (e) {
        // Fall back to default
      }
    }
  } catch (e) {
    // Fall back to default
  }
  
  // Return default structure matching sidebars.ts
  return [
    {
      id: 'sidebar-home',
      type: 'link',
      label: 'Home',
      href: '/',
    },
    {
      id: 'sidebar-platform',
      type: 'category',
      label: 'Platform Fundamentals',
      link: { type: 'generated-index' },
      collapsible: true,
      collapsed: false,
      items: [
        {
          id: 'sidebar-platform-doc',
          type: 'autogenerated',
          dirName: '01-platform-fundamentals',
        },
      ],
    },
    {
      id: 'sidebar-account',
      type: 'category',
      label: 'Account Management',
      link: { type: 'generated-index' },
      collapsible: true,
      collapsed: true,
      items: [
        {
          id: 'sidebar-account-doc',
          type: 'autogenerated',
          dirName: '02-account-management',
        },
      ],
    },
    {
      id: 'sidebar-network',
      type: 'category',
      label: 'Network Requirements',
      link: { type: 'generated-index' },
      collapsible: true,
      collapsed: true,
      items: [
        {
          id: 'sidebar-network-doc',
          type: 'autogenerated',
          dirName: '03-network-requirements',
        },
      ],
    },
    {
      id: 'sidebar-device',
      type: 'category',
      label: 'Device Integration',
      link: { type: 'generated-index' },
      collapsible: true,
      collapsed: true,
      items: [
        {
          id: 'sidebar-device-doc',
          type: 'autogenerated',
          dirName: '04-device-integration',
        },
      ],
    },
    {
      id: 'sidebar-features',
      type: 'category',
      label: 'Features & Operations',
      link: { type: 'generated-index' },
      collapsible: true,
      collapsed: true,
      items: [
        {
          id: 'sidebar-features-doc',
          type: 'autogenerated',
          dirName: '05-features-operations',
        },
      ],
    },
    {
      id: 'sidebar-ai',
      type: 'category',
      label: 'AI & False Alarm Filtering',
      link: { type: 'generated-index' },
      collapsible: true,
      collapsed: true,
      items: [
        {
          id: 'sidebar-ai-doc',
          type: 'autogenerated',
          dirName: '06-ai-false-alarm-filtering',
        },
      ],
    },
    {
      id: 'sidebar-workflows',
      type: 'category',
      label: 'Workflows & Automation',
      link: { type: 'generated-index' },
      collapsible: true,
      collapsed: true,
      items: [
        {
          id: 'sidebar-workflows-doc',
          type: 'autogenerated',
          dirName: '07-workflows-automation',
        },
      ],
    },
    {
      id: 'sidebar-support',
      type: 'category',
      label: 'Troubleshooting & Support',
      link: { type: 'generated-index' },
      collapsible: true,
      collapsed: true,
      items: [
        {
          id: 'sidebar-support-doc',
          type: 'autogenerated',
          dirName: '08-troubleshooting-support',
        },
      ],
    },
    {
      id: 'sidebar-internal',
      type: 'category',
      label: 'Internal Docs',
      collapsible: true,
      collapsed: true,
      items: [
        {
          id: 'sidebar-internal-doc',
          type: 'autogenerated',
          dirName: 'internal',
        },
      ],
    },
  ];
}

